### ISSUE TITLE
Some small changes i want to know about

### ISSUE THREAD

**Issue by Wisam97** [mtadayz/MTADayZ#63] opened 2016-06-24 21:52 UTC
- The night time is too dark.. i mean i tried to lower it in the files but nothing made it as i want it, also the night goggles are almost useless you can try it yourself.
- Is it possible to edit the zombie system i want to make it that the zombies spawn in specific positions not spawning close to the players.. i want to spawn zombies to their suitable places like zombie doctors at hospitals, zombie soldeirs at military areas and so on.

**Comment by ghost** [comment] 2016-06-24 21:57
Your request has been received. I'll try to do my best to satisfy you.

Thanks,
Rémi

**Comment by Wisam97** [comment] 2016-06-26 10:04
Thanks alot man i appreciate your help.. but i still want to change the zombie spawn mode for my gamemode no need to do it yourself i can do it but just give me a little help like where should i look :)

**Comment by 0xCiBeR** [comment] 2016-06-26 13:09
The zombie spawn overhaul is a pending task from way before you asked for it. It'll be done at some point, but don't bug the devs so they can do it faster. Check out issue #27

**Comment by ghost** [comment] 2016-06-26 17:59
And the night was slightly improved by 1.9.7.2a (8edd9be) patch, is better on your side? You can reduce the effect of the night by increasing the value of the variable "**maxDarkness**" in the file: "**DayZ/handlers/world/client/night/c_night.lua**".

And for the problem with night visions, a issue has been open about it #65.

**Edit :** Issue #65 fixed by 0.9.7.3a !

**Comment by ghost** [comment] 2016-07-18 15:27
The issue is now closed. The night has been improved and the new zombie system is provided by issue #27.

**Closed as completed by ghost** 2016-07-18 15:27 UTC
Labels: feedback
