### ISSUE TITLE
Little Item Problems, Glitche's, Bug's? Report it here!.

### ISSUE THREAD

**Issue by xboxxxxd** [mtadayz/MTADayZ#87] opened 2016-07-13 17:53 UTC
Report your Item Glitche's, Bug's, etc here!,
May a Screenshot of the Problem being made, post it aswel with it!.
If possible, Show for certain one's Like 2 Picture's, one of it's working, other one it's broken, An Example of mine i found down below!.

Item: Hatchet.
Problem: Break's Inventory GUI when putting Hatchet into Tent.

Normal:
![working](https://cloud.githubusercontent.com/assets/6675843/16813747/cdec7a1c-48e7-11e6-99b5-64fcd4e141ff.png)

Broken:
![broken](https://cloud.githubusercontent.com/assets/6675843/16813746/cde794fc-48e7-11e6-80c5-983ccea5e7fa.png)

**Comment by ghost** [comment] 2016-07-13 17:56
Dear xboxxxxd,

Thank you for the report. Thank you for helping us improve MTA DayZ.

Rémi Gaffet

**Comment by xboxxxxd** [comment] 2016-07-13 18:13
Looting gives Broken Inventory sometimes, Thinking about an Item causing this issue:

![looting gives broken inventory sometimes problably an item is the issue](https://cloud.githubusercontent.com/assets/6675843/16814433/b026f2f2-48ea-11e6-8b5d-b398fdfe6885.png)

**Comment by ghost** [comment] 2016-07-13 19:34
The problem is completely random. Sometimes the loots of points can work, sometimes it does not.

**Comment by xboxxxxd** [comment] 2016-07-13 20:14
There is 1 item, it has no Description, no Name, nothing, it looks like a piece of clothes,
assuming of the picture next to it's item name,
If i se it again, i screenshot it.

Greetings.xboxxxxd

**Comment by 0xCiBeR** [comment] 2016-07-21 22:31
Any news on this?

**Comment by ghost** [comment] 2016-07-22 18:03
For now, I is not yet identified the causes of the problem.

**Comment by xboxxxxd** [comment] 2016-07-29 14:55
Ive noticed sometimes when you tab a weapon from your inventory to on the ground, or other way arround.. it still keep's bypassing Battldayz addon.. Not sure why, it's like an item duplication glitch..
It happens the most with ammo for weapons.
I wil try to record this whenever i can, just a short video to post here..

EDIT: It does this after the Battldayz addon response's to the glitch when it give's the warning...
After that, keep trying and you break your inventory.. but the last part is the client's own fault.

Greetings.xboxxxxd

**Comment by 0xCiBeR** [comment] 2016-08-16 02:40
BattleDayZ doen't check against duping. MTA:DayZ's core does. Could you please post a video?

Thx.

**Comment by 0xCiBeR** [comment] 2016-09-25 01:40
No feedback recived. Closing this, in case of more info please open a new issue

**Closed as completed by 0xCiBeR** 2016-09-25 01:40 UTC
Labels: bug, feedback
